config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pets#index"

  resources :pets
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
  validates :age, presence: true, numericality: true
  validates :breed, presence: true

  has_attached_file :photo,
                    styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: "/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  # Returns the paperclip photo url
  def photo_url
    photo.url
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  has_many :pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!
  respond_to :json

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @pet.to_json(methods: :photo_url)}
    end
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = current_user.pets.new(entry_params)

    if @pet.save
      redirect_to root_path,
                  flash: { success: "Pet has been saved successfully."}
    else
      render 'new', flash: { error: "Pet has not been saved."}
    end
  end

  def edit
    @pet = Pet.find(params[:id])
    user = User.find(@pet.user_id)
    if user != current_user
      redirect_to root_path, flash: { error: "Only owner can edit its pet" }
    end
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update_attributes(entry_params)
       redirect_to root_path,
                   flash: { :success => "Pet has been updated successfully." }
    else
      redirect_to root_path, :flash => { :error => "Pet has not been updated." }
    end
  end

  def destroy
    pet = Pet.find(params[:id])
    user = User.find(pet.user_id)
    if user == current_user
      pet.destroy
      redirect_to root_path,
                  flash: { success: "Pet has been deleted successfully."}
    else
      redirect_to root_path, flash: { error: "Only owner can delete its pet" }
    end
  end

  private
  def entry_params
    params.require(:pet).permit(:name, :age, :breed, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>GroopiePets</title>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <nav>
      <div class="nav-wrapper">
        <%= link_to "GroopiePets", root_path, class: "brand-logo" %>
        <a href="#" data-activates="mobile-menu" class="button-collapse">
          <i class="material-icons">menu</i>
        </a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "New Pet", new_pet_path, method: :get %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
        <ul class="side-nav" id="mobile-menu">
          <li><%= link_to "New Pet", new_pet_path, method: :get %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </nav>
  </header>

  <main>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>

    </div>
  </main>

  <footer class="page-footer">
    <div class="footer-copyright">
      <div class="container">
      © 2015 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/pets/_pet_form.html.erb
<%= form_for @pet do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <br>
  <%= form.label :breed %>
  <%= form.text_field :breed %>
  <br>
  <%= form.label :age %>
  <%= form.text_field :age %>
  <br>
  <%= form.label :photo %>
  <%= form.file_field :photo %>
  <br>
  <%= form.submit 'Save' %>
<% end %>

app/views/pets/edit.html.erb
<%= render 'pet_form' %>

app/views/pets/index.html.erb
<div>
  <!-- Pets list -->
  <table>
    <thead>
      <tr>
        <th data-field="id">Pet Name</th>
      </tr>
    </thead>

    <tbody>
      <% @pets.each do |pet| %>
        <tr>
          <td>
            <a class="js-get-detail" data-pet-id="<%= pet.id %>" href="#" >
              <%= pet.name %>
            </a>
          </td>
          <td>
            <%= link_to "Detail", pet_path(pet.id)%>
          </td>
          <td>
            <%= link_to "Edit", edit_pet_path(pet) %>
          </td>
          <td>
            <%= link_to "Delete", pet_path(pet.id), method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- Modal Detal Window -->
  <div id="petDetailModal" class="modal">
    <div class="modal-content">
      <h4 class="js-pet-name"></h4>
      <p class="js-pet-description"></p>
      <img id="js-pet-img" class="responsive-img" />
    </div>
    <div class="modal-footer">
      <a href="#!"class="modal-action modal-close waves-effect waves-green btn-flat">
        Close
      </a>
    </div>
  </div>
</div>

app/views/pets/new.html.erb
<h2>New Pet</h2>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= render 'pet_form' %>

app/views/pets/show.html.erb
<div class="pet-detail">
  <p class="flow-text center">
    Name: <%= @pet.name %><br>
    Breed: <%= @pet.breed %><br>
    Age: <%= @pet.age %> years
  </p>

  <img class="materialboxed responsive-img pet-img" src="<%= @pet.photo.url %>">
</div>